USE [master]
GO
ALTER DATABASE [tempdb] SET PAGE_VERIFY NONE  WITH NO_WAIT
GO
ALTER DATABASE [tempdb] SET DELAYED_DURABILITY = ALLOWED WITH NO_WAIT
GO
ALTER DATABASE [tempdb] SET AUTO_UPDATE_STATISTICS OFF WITH NO_WAIT
GO
ALTER DATABASE [tempdb] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT
GO
